apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit
  namespace: finamer
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-finamer-audit
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: audit
        workload.user.cattle.io/workloadselector: apps.deployment-finamer-audit
      namespace: finamer
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: audit-secret
                optional: false
          image: tailorw/erp-audit:dev
          imagePullPolicy: Always
          name: audit
          ports:
            - containerPort: 9909
              name: http
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dokcer-hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
