apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-card
  namespace: finamer
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-finamer-credit-card
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: credit-card
        workload.user.cattle.io/workloadselector: apps.deployment-finamer-credit-card
    spec:
      containers:
        - name: credit-card
          image: tailorw/fin-credit-card:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9905
              name: http
              protocol: TCP
          envFrom:
            - secretRef:
                name: credit-card-secret
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dokcer-hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30