apiVersion: v1
kind: Service
metadata:
  name: postgres-pointsales-ro-ext
  namespace: postgres
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: postgres-pointsales
    cnpg.io/instanceRole: replica
  ports:
    - name: postgres
      nodePort: 32502
      port: 5432
      protocol: TCP
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-pointsales-rw-ext
  namespace: postgres
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: postgres-pointsales
    cnpg.io/instanceRole: primary
  ports:
    - name: postgres
      nodePort: 32503
      port: 5432
      protocol: TCP
      targetPort: 5432