apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: finamer
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
    - name: http
      port: 8097
      protocol: TCP
      targetPort: 9909

