apiVersion: v1
data:
  ELASTIC_SEARCH_PASSWORD: M1dUMnR5RlV6YVpXS0FEbA==
  ELASTIC_SEARCH_URL: ZWxhc3RpY3NlYXJjaC5lbGFzdGljLWRldi5zdmMuY2x1c3Rlci5sb2NhbDo5MjAw
  ELASTIC_SEARCH_USERNAME: ZWxhc3RpYw==
  KAFKA_BOOSTRAP_SERVER: a2Fma2Eua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mg==
  KAFKA_GROUP_ID: YXVkaXQ=
  RC_ACTIVE_PROFILE: ZGV2ZWxvcG1lbnQ=
  RC_SERVER_CONFIG: Y29uZmlnLXNlcnZpY2U=
  REDIS_ADDRESS: cmVkaXMtc2VydmljZS5jYWNoZS5zdmMuY2x1c3Rlci5sb2NhbA==
  REDIS_PORT: NjM3OQ==
kind: Secret
metadata:
  creationTimestamp: '2024-10-23T20:03:44Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ELASTIC_SEARCH_PASSWORD: {}
          f:ELASTIC_SEARCH_URL: {}
          f:ELASTIC_SEARCH_USERNAME: {}
          f:KAFKA_BOOSTRAP_SERVER: {}
          f:KAFKA_GROUP_ID: {}
          f:RC_ACTIVE_PROFILE: {}
          f:RC_SERVER_CONFIG: {}
          f:REDIS_ADDRESS: {}
          f:REDIS_PORT: {}
        f:type: {}
      manager: rancher
      operation: Update
      time: '2024-10-25T21:42:17Z'
  name: audit-secret
  namespace: finamer
  resourceVersion: '51156146'
  uid: 825ce778-f273-4cc4-8a3f-d16b0f1ab482
