apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  namespace: pointsales
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-pointsales-identity
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: identity
        workload.user.cattle.io/workloadselector: apps.deployment-pointsales-identity
    spec:
      containers:
        - name: pointsales
          image: tailorw/pointsales-identity:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 9905
              name: http
              protocol: TCP
          envFrom:
            - secretRef:
                name: identity-secret
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker-hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30