apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-user-secret
  namespace: keycloak
type: kubernetes.io/basic-auth
data:
  username: a2V5Y2xvYWs=
  password: a2V5Y2xvYWs=
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
   name: keycloak-cluster
   namespace: keycloak
spec:
   instances: 2
   imageName: ghcr.io/cloudnative-pg/postgresql:16.3
   bootstrap:
      initdb:
         database: keycloak
         owner: keycloak
         secret:
            name: keycloak-postgres-user-secret
   affinity:
      tolerations:
      -   key: "role"
          value: "bdd"
          effect: "NoSchedule"
   postgresql:
      parameters:
         shared_buffers: "256MB"
   resources:
      requests:
         memory: 1Gi
         cpu: 1
      limits:
         memory: 2Gi
         cpu: 1
   storage:
      size: 50Gi
