apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-user-secret
  namespace: keycloak
type: kubernetes.io/basic-auth
data:
  username: a2V5Y2xvYWs=
  password: a2V5Y2xvYWs=
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
   name: keycloak-cluster
   namespace: keycloak
spec:
   instances: 2
   imageName: ghcr.io/cloudnative-pg/postgresql:16.11
   bootstrap:
      initdb:
         database: keycloak
         owner: keycloak
         secret:
            name: keycloak-postgres-user-secret
   affinity:
      nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ecdsagent03
                - ecdsagent04
      podAntiAffinityType: preferred
      tolerations:
      - key: "role"
        operator: "Equal"
        value: "bdd"
        effect: "NoSchedule"
   postgresql:
      parameters:
         shared_buffers: "512MB"
         effective_cache_size: "1536MB"
         maintenance_work_mem: "128MB"
         wal_buffers: "16MB"
   resources:
      requests:
         memory: 1Gi
         cpu: 500m
      limits:
         memory: 2Gi
         cpu: 2
   storage:
      size: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-cluster
  namespace: keycloak
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: keycloak-cluster
    cnpg.io/instanceRole: primary
  ports:
  - name: postgres
    nodePort: 32501
    port: 5432
    protocol: TCP
    targetPort: 5432



