apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: finamer
spec:
  type: ClusterIP
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  
