apiVersion: v1
kind: Namespace
metadata:
  name: cache
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: cache
data:
  redis-config: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: redis
   namespace: cache
spec:
   replicas: 1
   selector:
      matchLabels:
         app: redis-cache
   template:
      metadata:
         labels:
            app: redis-cache
      spec:
         containers:
         - name: redis
           image: redis:5.0.4
           command:
           - redis-server
           - "/redis-master/redis.conf"
           env:
           - name: MASTER
             value: "true"
           ports:
           - containerPort: 6379
           resources:
              limits:
                 cpu: "0.1"
           volumeMounts:
           - name: data
             mountPath: /redis-master-data
           - name: config
             mountPath: /redis-master
         volumes:
         - name: data
           emptyDir: {}
         - name: config
           configMap:
              name: redis-config
              items:
              - key: redis-config
                path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-cache
  namespace: cache
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6379
      targetPort: 6379
  selector:
    app: redis-cache
