apiVersion: v1
kind: Secret
metadata:
  name: cloudbridges-secret
  namespace: pointsales
type: Opaque
data:
  RC_ACTIVE_PROFILE: ZGV2ZWxvcG1lbnQ=
  RC_SERVER_CONFIG: Y29uZmlnLXNlcnZpY2U=
  SERVER_PORT: OTkwOQ==
  DB_HOST_RW: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtcG9pbnRzYWxlcy1ydy5wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3BvaW50c2FsZXMtY2xvdWRicmlkZ2Vz
  DB_HOST_R: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtZXJwLXJvLnBvc3RncmVzLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvZmluYW1lci1jbG91ZGJyaWRnZXM=
  DB_USER_RW: dXNyZHNiZGRfcnc=
  DB_USER_R: dXNyZHNiZGRfcm8=
  DB_PASSWORD_RO: VG1acFZGaExhRUYyWnpRM1pUQnY=
  DB_PASSWORD_RW: UlVOVVN6RjRhSGd4ZG05YU1USXM=
  REDIS_ADDRESS: cmVkaXMtc2VydmljZS5jYWNoZS5zdmMuY2x1c3Rlci5sb2NhbA==
  REDIS_PORT: NjM3OQ==
  KAFKA_BOOTSTRAP_ADDRESS: a2Fma2Eua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mg==
  KAFKA_GROUP_ID: Q0xPVURCUklER0VT
  AWS_ACCESS_SECRET: MzQ0MjljMWIwY2FjNWQ4YTM4YTk1N2FiY2U4ZDk3MmQwOWY3YzBhZWYxODZhMGFlZjdmYzhhNzg1ZDZlNTQ3OA==
  AWS_ACCESS_KEY: YjUzM2M0ZDdiM2UxMWMyY2JiZDZmMzEyMzhkYjdjYTk=
  MAILJET_KEY: YWQzZDYzNWRkYWYyODhiM2M2MTExYjM3Y2VmYjFkNGE=
  MAILJET_SECRET: NDFhNjVkM2ViNTViMjRjMmRiMmQ5ZjdkZmY1NGE3Njc=
