apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: pointsales
spec:
  type: ClusterIP
  selector:
    app: config
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  
